### ISSUE TITLE
Cannot allocate color 'none'

### ISSUE THREAD

**Issue by robdelacruz** [danishprakash/vim-yami#1]
I get the error: Cannot allocate color 'none' in VIM 8.0

To fix, replace all 'none' with 'NONE' in yami.vim:
:%s/none/NONE/g

I think Vim uses 'NONE' while NeoVim color comparison is case insensitive. I don't have NeoVim to test it on.

Thanks for the theme. Been looking for a monochrome color scheme like this one.

**Comment by hanneskaeufler** [comment]
Can confirm both the error and the quickfix with

```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Jun 12 2019 19:31:20)
macOS version
Included patches: 1-1517
Compiled by Homebrew
```

**Comment by danishprakash** [comment]
@robdelacruz Thanks for reporting this. 
I was not able to test it on Vim, It should work now. @hanneskaeufler
